[package]
name = "csvtoron"
version = "0.2.0"
edition = "2018"
license = "MIT"
author = ["Hartmut Prochaska <hartmut.prochaska@gmail.com>"]

[lib]
name = "csvtoron"

[dependencies]
ron = "0.6.5"
serde = { version = "1", features = ["derive"] }
csv = "1.1"

[[example]]
name = "converter"
